# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a4155074df394843f13ae458a2c48b7559143ec03e157c8a061cd0ecbc7f6f3ab4868d8fa037f584a386e57df27c8a75375f02a83a1f74fb2f25c69825772d3

test:
  secret_key_base: 37ca5e183adc86c2543950e35269ced8c42272dcd8dccd555665d47fcfa2adfd8ab666b4a4d8cf671c71d7b7699ec306a29b72d99b427eac2b922188302af6d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
